package com.example.preppal

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class Meals(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    @ColumnInfo(name = "mealName") val Meal: String,
    @ColumnInfo(name = "drinkAlternate") val DrinkAlternate: String?,
    @ColumnInfo(name = "Category") val Category: String?,
    @ColumnInfo(name = "area") val Area: String?,
    @ColumnInfo(name = "instructions") val Instructions: String?,
    @ColumnInfo(name = "mealThumb") val MealThumb: String?,
    @ColumnInfo(name = "tags") val Tags: String?,
    @ColumnInfo(name = "youtubeLink") val YoutubeLink: String?,
    @ColumnInfo(name = "ingredient1") val Ingredient1: String?,
    @ColumnInfo(name = "ingredient2") val Ingredient2: String?,
    @ColumnInfo(name = "ingredient3") val Ingredient3: String?,
    @ColumnInfo(name = "ingredient4") val Ingredient4: String?,
    @ColumnInfo(name = "ingredient5") val Ingredient5: String?,
    @ColumnInfo(name = "ingredient6") val Ingredient6: String?,
    @ColumnInfo(name = "ingredient7") val Ingredient7: String?,
    @ColumnInfo(name = "ingredient8") val Ingredient8: String?,
    @ColumnInfo(name = "ingredient9") val Ingredient9: String?,
    @ColumnInfo(name = "ingredient10") val Ingredient10: String?,
    @ColumnInfo(name = "ingredient11") val Ingredient11: String?,
    @ColumnInfo(name = "ingredient12") val Ingredient12: String?,
    @ColumnInfo(name = "ingredient13") val Ingredient13: String?,
    @ColumnInfo(name = "ingredient14") val Ingredient14: String?,
    @ColumnInfo(name = "ingredient15") val Ingredient15: String?,
    @ColumnInfo(name = "ingredient16") val Ingredient16: String?,
    @ColumnInfo(name = "ingredient17") val Ingredient17: String?,
    @ColumnInfo(name = "ingredient18") val Ingredient18: String?,
    @ColumnInfo(name = "ingredient19") val Ingredient19: String?,
    @ColumnInfo(name = "ingredient20") val Ingredient20: String?,
    @ColumnInfo(name = "measure1") val Measure1: String?,
    @ColumnInfo(name = "measure2") val Measure2: String?,
    @ColumnInfo(name = "measure3") val Measure3: String?,
    @ColumnInfo(name = "measure4") val Measure4: String?,
    @ColumnInfo(name = "measure5") val Measure5: String?,
    @ColumnInfo(name = "measure6") val Measure6: String?,
    @ColumnInfo(name = "measure7") val Measure7: String?,
    @ColumnInfo(name = "measure8") val Measure8: String?,
    @ColumnInfo(name = "measure9") val Measure9: String?,
    @ColumnInfo(name = "measure10") val Measure10: String?,
    @ColumnInfo(name = "measure11") val Measure11: String?,
    @ColumnInfo(name = "measure12") val Measure12: String?,
    @ColumnInfo(name = "measure13") val Measure13: String?,
    @ColumnInfo(name = "measure14") val Measure14: String?,
    @ColumnInfo(name = "measure15") val Measure15: String?,
    @ColumnInfo(name = "measure16") val Measure16: String?,
    @ColumnInfo(name = "measure17") val Measure17: String?,
    @ColumnInfo(name = "measure18") val Measure18: String?,
    @ColumnInfo(name = "measure19") val Measure19: String?,
    @ColumnInfo(name = "measure20") val Measure20: String?,
)
